[WIP] Fix propagation
brndnmtthws/conky pull request #1802
Opened 2024-04-06 15:28 UTC by Caellian

Events now get correctly propagated to a window (or desktop if none) _behind_ conky instead of always to desktop.

This PR addresses some of the issues raised in #1767.

This was a necessary change to handle cases such as MATE+caja where caja is used between conky and background to show icons and desktop menu.

- [x] Fix click-through for openbox
- [ ] Fix click-through for MATE
- [ ] Check for regression in other WM/DEs

2024-04-06 15:45 UTC, Caellian commented on src/x11.cc
> -    XSetInputFocus(display, window.desktop, RevertToPointerRoot, time);
We don't capture keyboard focus anyway (yet?).

2024-04-06 15:47 UTC, Caellian commented on src/x11.cc
> +  //   XSetInputFocus(display, i_ev->common.window, RevertToPointerRoot, time);
Leaving this for later. Conky doesn't capture keyboard focus (yet?).

2024-04-06 15:59 UTC, Caellian commented
Detecting the window below conky breaks openbox because it does something _weird_ with the window tree:
```
0x201369 (has no name): ()  253x102+44+44  +44+44
        24 children:
        0x2200001 "conky (torchwood)": ("Conky" "Conky")  253x102+0+0  +44+44
        0x201395 (has no name): ()  1x1+0+0  +44+44
        0x201394 (has no name): ()  1x1+0+0  +44+44
        0x201393 (has no name): ()  1x1+0+0  +44+44
        0x201392 (has no name): ()  1x1+0+0  +44+44
        0x201391 (has no name): ()  1x1+0+0  +44+44
        0x201390 (has no name): ()  1x1+0+0  +44+44
        0x20138f (has no name): ()  1x1+0+0  +44+44
        0x20138e (has no name): ()  1x1+0+0  +44+44
        0x201389 (has no name): ()  1x1+0+0  +44+44
```

I've seen a similar thing happen on Plasma...

2024-04-06 20:18 UTC, Caellian commented
> openbox [...] it does something weird with the window tree

Not sure what it is, spent an hour looking for it online but there's no mention of it anywhere. I left the previous impl as a fallback and rely on atoms instead now - so openbox works again. I think `_NET_CLIENT_LIST` "SHOULD" be common enough. There's ways to improve correctness (like manual ordering based on depth in window attributes if `_NET_CLIENT_LIST_STACKED` is not defined), but I'm burnt out for now and they seem wasteful.

MATE still doesn't work, that's next I guess.

2024-04-08 10:07 UTC, Caellian commented
MATE uses caja, which uses gtk. No events get properly passed through, but I'm focusing on right-click which should open a context menu.

Gdk starts handling menu opening with `gdk_x11_toplevel_show_window_menu`, in `gdk/x11/gdksurface-x11.c`, which is then translated into a GdkEvent (through very complicated and long pipeline of handlers,signals,converters,...), but up to the point where high level "get events" function is, nothing seems to be checking whether the right-clicked surface is below pointer, nor whether the click event was synthetic (which was my previous hunch).

It seems Gdk only accepts Xinput pointer events, which is why it ignores the basic X11 ones.

2024-04-08 15:28 UTC, brndnmtthws requested changes
PR looks good, one minor nit.

2024-04-08 16:50 UTC, Caellian commented on src/x11.cc
> +  // int _revert_to;
Removed.

2024-04-08 16:52 UTC, Caellian commented on src/x11.cc
> +  // int _revert_to;
No, wait, just realized that event coordinates are global even if window isn't root.

2024-04-08 17:00 UTC, Caellian commented on src/x11.cc
> +  // int _revert_to;
Ok, now it's ~done. I'm adding propagation of Xinput events on a separate branch, that should hopefully fix MATE/GDK.

2024-04-09 11:59 UTC, brndnmtthws approved these changes

2024-04-09 12:28 UTC, merged