Fix AC/battery detection logic on FreeBSD.
brndnmtthws/conky pull request #1972
Opened 2024-06-13 16:00 UTC by fernape

The logic for the detection of the battery/AC line was not completely correct for FreeBSD. Launching conky on console shows the following:

Cannot read sysctl "hw.acpi.battery.time"
Cannot read sysctl "hw.acpi.battery.life"
Cannot read sysctl "hw.acpi.battery.state"
Cannot read sysctl "hw.acpi.acline"
Unknown battery state 8!

In a PC, the hw.acpi.battery MIB does not exist.
Also, the hw.acpi.acline is only present if supported by the hardware. In addition, some variables were used uninitialized and that causes strange behavior: in a PC it showed it worked on battery and the % of charge was an ridiculous big number.

![bad](https://github.com/brndnmtthws/conky/assets/2565871/d3bfb54e-7eca-4e3b-8fcc-72d61639291e)

This patch addresses the issue. It fixes the problem in the PC. It has also being tested in a laptop running FreeBSD current plugin and unplugging the AC line and also snatching the battery mercilessly to see if something breaks.

![good](https://github.com/brndnmtthws/conky/assets/2565871/b4d07447-6415-46c5-b190-38114dcf2c1e)

# Checklist
- [x] I have described the changes
- [x] I have linked to any relevant GitHub issues, if applicable
- [x ] Documentation in `doc/` has been updated
- [x] All new code is licensed under GPLv3

## Description

* Describe the changes, why they were necessary, etc
* Describe how the changes will affect existing behaviour.
* Describe how you tested and validated your changes.
* Include any relevant screenshots/evidence demonstrating that the changes work and have been tested.

2024-06-14 17:13 UTC, brndnmtthws requested changes
Overall it's good, but since you're making changes here we should replace those `fprintf()` calls with [`NORM_ERR`](https://github.com/brndnmtthws/conky/blob/33903e7d6c4681b4f842dc39755e3a4a72f34185/src/logging.h#L76-L81) instead, if you wouldn't mind.

2024-06-14 17:13 UTC, brndnmtthws commented on src/freebsd.cc
> +      fprintf(stderr, "Cannot read sysctl \"hw.acpi.battery.time\"\n");
```suggestion
      NORM_ERR("Cannot read sysctl \"hw.acpi.battery.time\"");
```

2024-06-14 17:52 UTC, fernape commented
> Overall it's good, but since you're making changes here we should replace those `fprintf()` calls with [`NORM_ERR`](https://github.com/brndnmtthws/conky/blob/33903e7d6c4681b4f842dc39755e3a4a72f34185/src/logging.h#L76-L81) instead, if you wouldn't mind.

Thank you for the suggestion. I didn't know about `NORM_ERROR` and the `fprintf()` were already there. I'll take that into account.

2024-06-15 00:46 UTC, brndnmtthws approved these changes

2024-06-15 00:47 UTC, merged