[WIP] Fix NetBSD build.
brndnmtthws/conky pull request #2089
Opened 2024-11-22 12:24 UTC by g0mb4

Waiting for #2080.

Using NetBSD 10.0.

![image](https://github.com/user-attachments/assets/ec33c03e-3632-415b-a089-c5c0f50a7be0)

Compiling with: `cmake -DBUILD_IMLIB2=OFF ..`

There are a lot of `TODO`s, but it compiles.

2024-11-22 15:40 UTC, g0mb4 commented
Sure. I'll do the rebasing, just wanted to save my work and signal that I'm working on it.

2024-11-22 16:03 UTC, g0mb4 commented
And sorry for the inconvinience, but now I have time to work on it. I do not mind rebasing and fixing the conflicts.

2024-11-23 00:02 UTC, Caellian commented
> And sorry for the inconvinience.

Not an inconvenience. I just warned you because I did the same thing in one of my first commits and it ended up being such a mess that I had to abandon the PR and create a new one with no history (just one example).

Anyway, merged the other branch and rebased this one (reminder to pull before making the next commit), only a single conflict.

2024-11-23 00:34 UTC, Caellian requested changes
Minor change requests

2024-11-23 00:34 UTC, Caellian commented on cmake/ConkyPlatformChecks.cmake
> +  set(conky_libs ${conky_libs} -lkvm -lintl -lossaudio)
- `-lintl` not needed.
- `-lossaudio` should be handled  on line 159 in this file presumably by adding `OR OS_NETBSD` to `elseif(OS_OPENBSD)`

2024-11-23 00:34 UTC, Caellian commented on cmake/ConkyPlatformChecks.cmake
> +  endif(OS_NETBSD)
This whole `BUILD_NCURSES` block should really do what [this patch for weechat on NetBSD does](http://cvsweb.netbsd.org/bsdweb.cgi/pkgsrc/chat/weechat/patches/patch-cmake_FindNcurses.cmake?rev=1.1&content-type=text/x-cvsweb-markup) - check for both `ncurses` and `curses`.

2024-11-25 11:47 UTC, Caellian requested changes

2024-11-25 11:47 UTC, Caellian commented on cmake/ConkyPlatformChecks.cmake
> +    NAMES ncurses
Replace with `curses`. `ncurses` is open-source distribution of `curses`, `ncurses` must provide `curses` (or it's an error made by package author)

2024-11-25 11:47 UTC, Caellian commented on cmake/ConkyPlatformChecks.cmake
> +    NAMES ncurses.h curses.h
Check only for `curses.h`, we want to be evil and fail here if `ncurses.h` exists and `curses.h` re-export doesn't (it shouldn't; checked on Arch, NetBDS diff also replaces it with `curses.h`).

2024-11-25 23:19 UTC, Caellian approved these changes
CI still builds for other platforms, LGTM.

2024-11-25 23:21 UTC, merged